### ISSUE TITLE
Is still working?

### ISSUE THREAD

**Issue by TheRhanderson** [Askwrite/node-csgo-reportbot#27]
Hello,

There are a lot of people with a lot of questions about this yet.
There are times when the report works and sometimes it does not, and you have doubts.

Could anyone give an accurate position on this?
Thanks in advance!

**Comment by toopski** [comment]
it still works with accounts that have no vac or ow bans and it's on something like a once per 12 hour kind of thing

however the updater.js file included has a link to gather some files that were moved so it will not install correctly using that and you will need to either track down the files manually or like I did update the files to gather from the new source

**Comment by 123top** [comment]
Can you explain it in more detail pls? It seems like the bot is broke. Reporting a spinner and he is not banned after 21 hours.

**Comment by toopski** [comment]
If you only installed it and did all the stuff recently when running the updater.js file which is now done automatically with npm install, you get some files but they will be blank causing a 404 error due to the location of the files they tried to copy having been moved and the link in updater.js not being corrected
